### ISSUE TITLE
Looking for js sf2 player

### ISSUE THREAD

**Issue by JanVeb** [felixroos/sfumato#2]
Servus,
Already for some time I'm looking for js sf2 player, at the moment I'm using this one: https://github.com/enjikaka/sf2-player, and while it is great as it sounds better than anything else I tried (didn't found sf2 alternative, but non sf2 alternatives can't compare in sound quality), it introduces some annoying cracking sounds, which aren't that obvious , but they are still obvious especially to me as I'm listening it on daily basis. There are some other issues, but not as critical.

So I found this project and it looks promising, it sounds amazing, seems you really know what you are doing to pull juice out of it. Since there is no any documentation about how to implement it yet, wanted to ask is it possible already to use it, from demo it seems it works rather well.

If it works, would you share some code about how to import, load sf2 and noteOn and noteOff?

**Comment by JanVeb** [comment]
https://github.com/kevinsqi/react-piano

Playing around with your demo, thought maybe you would find this keyboard interesting, it plays instantly as key is pressed down and as swell plays the sound for as long a key is pressed down, also one can slide through the keys and they all will play, which is really sweet as I tried to do that with my own keyboard but couldn't figure this out.

**Comment by felixroos** [comment]
Hey! I am glad you find this lib does a good job :) It is pretty new and does not support the full sf2 spec, but I am adding the rest when I have time. ~~The doc is still TODO, but~~ it's actually not that complicated:

## Installation

```sh
npm i sfumato --save
```

## Import

```js
import { loadSoundfont, startPresetNote } from 'sfumato';
```

## API

- `loadSoundfount(url)` loads a soundfont from a url. returns [Soundfont2](https://mrtenz.github.io/soundfont2/api/soundfont2/)
- `startPresetNote(ctx, preset, midi, time)` plays a note, returns `stopHandle`
  - `ctx` the audio context to use
  - `preset` the preset to use (use one of [Soundfont2.presets](https://mrtenz.github.io/soundfont2/api/soundfont2/#soundfont2presets))
  - `midi` midi number to play
  - `time` audio context time to start playing (defaults to currentTime)
- `stopHandle(time)` stops the note at the given time

You can also [read how the demo does it](https://github.com/felixroos/sfumato/blob/main/demo/src/App.tsx#L90)

I know react-piano but I wanted to use my [own piano module](https://loophole-letters.vercel.app/claviature). It is possible to hold and slide keys but I did not bother to implement it as part of this demo.

May I ask for what you want to use this lib?

edit: I also added the above to the [readme](https://github.com/felixroos/sfumato#installation)

**Comment by JanVeb** [comment]
Thank,

Working on Piano flashcards app, basically splitting score into measures and then serving these pieces as a flashcards, so one can focus on parts that are harder to learn, with spaced repetition etc, you can check it out if interested on YouTube or at the moment only as android app.
https://www.youtube.com/watch?v=3qJH_S8aa5U
https://play.google.com/store/apps/details?id=org.example.pianotrainer

Will try tomorrow import sfumato and let you know how it went

**Comment by JanVeb** [comment]
I went with Howler for now, as have some other crucial issues to deal with at the moment and Howler gives me some nice options, though not sure it would be good for long run
